name = "RumaLean"
version = "0.1.0"
defaultTargets = ["RumaLean"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev = "fbfa185"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "RumaLean"
