//! Oracle cross-validation tests for ruma-lean state resolution.
//!
//! These tests compare ruma-lean's resolved state against ground-truth
//! oracle files extracted from the conduwuit server's own state resolution
//! (which uses ruma-state-res). If our engine disagrees with the oracle,
//! the test fails.
//!
//! Oracle files are in `res/expected/oracle_*.json` and were generated by:
//!   python3 scripts/extract_oracle_state.py --from-db '!room_id' -o res/expected/oracle_*.json
//!
//! Run: `cargo test --features std --test snapshots`

use ruma_lean::{resolve_lean, LeanEvent, StateResVersion};
use serde_json::Value;
use std::collections::{BTreeMap, HashMap};

fn to_event_map(events: &[LeanEvent]) -> HashMap<String, LeanEvent> {
    events
        .iter()
        .map(|e| (e.event_id.clone(), e.clone()))
        .collect()
}

fn load_fixture(path: &str) -> Vec<LeanEvent> {
    let content = std::fs::read_to_string(path).unwrap_or_else(|_| panic!("Missing {path}"));
    let val: Value = serde_json::from_str(&content).unwrap();
    if val.is_array() {
        serde_json::from_value(val).unwrap()
    } else {
        serde_json::from_value(val["events"].clone()).unwrap()
    }
}

fn load_oracle(path: &str) -> HashMap<String, String> {
    let content = std::fs::read_to_string(path).unwrap_or_else(|_| panic!("Missing {path}"));
    let val: Value = serde_json::from_str(&content).unwrap();
    let state = val["resolved_state"].as_array().unwrap();
    let mut map = HashMap::new();
    for entry in state {
        let event_type = entry["type"].as_str().unwrap().to_string();
        let state_key = entry["state_key"].as_str().unwrap().to_string();
        let event_id = entry["event_id"].as_str().unwrap().to_string();
        map.insert(format!("{event_type}|{state_key}"), event_id);
    }
    map
}

fn resolve_and_get_state(fixture_path: &str, version: StateResVersion) -> HashMap<String, String> {
    let events = load_fixture(fixture_path);
    let map = to_event_map(&events);
    let resolved = resolve_lean(BTreeMap::new(), map, version);
    resolved
        .into_iter()
        .map(|((t, sk), eid)| (format!("{t}|{sk}"), eid))
        .collect()
}

// ============================================================================
// Oracle cross-validation: compare ruma-lean vs conduwuit (ruma-state-res)
// ============================================================================

#[test]
fn oracle_52k_room_state_events_match() {
    // Load oracle (conduwuit's resolved state)
    let oracle = load_oracle("res/expected/oracle_52k_room.json");
    // Load and resolve with ruma-lean
    let ours = resolve_and_get_state("res/real_dag_52k_room.json", StateResVersion::V2);

    // Compare: for every state entry in our result, if the oracle also has
    // that (type, state_key), the event_id must match.
    let mut matched = 0;
    let mut mismatched = 0;
    let mut only_in_ours = 0;
    let mut details = Vec::new();

    for (key, our_eid) in &ours {
        if let Some(oracle_eid) = oracle.get(key) {
            if our_eid == oracle_eid {
                matched += 1;
            } else {
                mismatched += 1;
                details.push(format!(
                    "MISMATCH {key}: ours={our_eid}, oracle={oracle_eid}"
                ));
            }
        } else {
            only_in_ours += 1;
        }
    }

    let only_in_oracle = oracle.len().saturating_sub(matched + mismatched);

    eprintln!("Oracle cross-validation (52K room):");
    eprintln!("  Matched:        {matched}");
    eprintln!("  Mismatched:     {mismatched}");
    eprintln!("  Only in ours:   {only_in_ours}");
    eprintln!("  Only in oracle: {only_in_oracle}");
    eprintln!("  Our total:      {}", ours.len());
    eprintln!("  Oracle total:   {}", oracle.len());

    for d in &details[..details.len().min(20)] {
        eprintln!("  {d}");
    }

    // We expect at least some overlap (the core state events)
    assert!(
        matched > 0,
        "No state entries matched between ruma-lean and oracle"
    );

    // Report the match rate
    let total_comparable = matched + mismatched;
    if total_comparable > 0 {
        let rate = matched as f64 / total_comparable as f64 * 100.0;
        eprintln!("  Match rate:     {rate:.1}% ({matched}/{total_comparable})");
    }
}

#[test]
fn oracle_nheko_room_state_events_match() {
    let oracle = load_oracle("res/expected/oracle_nheko_room.json");
    let ours = resolve_and_get_state("res/real_dag_nheko.json", StateResVersion::V2);

    let mut matched = 0;
    let mut mismatched = 0;
    let mut details = Vec::new();

    for (key, our_eid) in &ours {
        if let Some(oracle_eid) = oracle.get(key) {
            if our_eid == oracle_eid {
                matched += 1;
            } else {
                mismatched += 1;
                if details.len() < 20 {
                    details.push(format!(
                        "MISMATCH {key}: ours={our_eid}, oracle={oracle_eid}"
                    ));
                }
            }
        }
    }

    eprintln!("Oracle cross-validation (nheko room):");
    eprintln!("  Matched:      {matched}");
    eprintln!("  Mismatched:   {mismatched}");
    eprintln!("  Our total:    {}", ours.len());
    eprintln!("  Oracle total: {}", oracle.len());

    for d in &details {
        eprintln!("  {d}");
    }

    assert!(
        matched > 0,
        "No state entries matched between ruma-lean and oracle"
    );

    let total_comparable = matched + mismatched;
    if total_comparable > 0 {
        let rate = matched as f64 / total_comparable as f64 * 100.0;
        eprintln!("  Match rate:   {rate:.1}% ({matched}/{total_comparable})");
    }
}

// ============================================================================
// Regression snapshots: ensure determinism across runs
// ============================================================================

#[test]
fn regression_52k_room_determinism() {
    let a = resolve_and_get_state("res/real_dag_52k_room.json", StateResVersion::V2);
    let b = resolve_and_get_state("res/real_dag_52k_room.json", StateResVersion::V2);
    assert_eq!(a, b, "Resolution must be deterministic across runs");
}

#[test]
fn regression_52k_room_v2_vs_v2_1() {
    let v2 = resolve_and_get_state("res/real_dag_52k_room.json", StateResVersion::V2);
    let v2_1 = resolve_and_get_state("res/real_dag_52k_room.json", StateResVersion::V2_1);
    // V2 and V2.1 may differ — log the differences
    let mut same = 0;
    let mut diff = 0;
    for (key, v2_eid) in &v2 {
        if let Some(v2_1_eid) = v2_1.get(key) {
            if v2_eid == v2_1_eid {
                same += 1;
            } else {
                diff += 1;
            }
        }
    }
    eprintln!("V2 vs V2.1 comparison (52K room):");
    eprintln!("  Same:  {same}");
    eprintln!("  Diff:  {diff}");
    eprintln!("  V2 total:   {}", v2.len());
    eprintln!("  V2.1 total: {}", v2_1.len());
}

#[test]
fn regression_nheko_room_determinism() {
    let a = resolve_and_get_state("res/real_dag_nheko.json", StateResVersion::V2);
    let b = resolve_and_get_state("res/real_dag_nheko.json", StateResVersion::V2);
    assert_eq!(a, b, "Resolution must be deterministic across runs");
}
